name: Cypress Heroes CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Instalar dependências do projeto
        run: npm install

      - name: Instalar dependências do client
        run: npm install
        working-directory: client

      - name: Configurar banco de dados
        run: npm run setup

      - name: Subir a aplicação em background
        run: npm run dev &
        
      - name: Aguardar aplicação iniciar
        run: npx wait-on http://localhost:3000 --timeout 60000

      - name: Executar testes Cypress
        run: npx cypress run
        working-directory: client